### ISSUE TITLE
coda_validate status buttons

### ISSUE THREAD

**Issue by ldko** [unt-libraries/coda#10]
@vphill would like to see green, red, and yellow buttons (similar to the ones on the index page of coda_mdstore but smaller) for the different validate statuses that are Passed, Failed, and Unverified. These might link to the entries that have the specified status. These buttons should be placed on the coda_validate index page at `/validate/` under the Coda Validate logo and above the "Prioritized Items" section.

**Comment by damonkelley** [comment]
What do the buttons do? Do they filter the list results?

**Comment by vphill** [comment]
They will just display high level information to us so that we can see how much has been validated, how much passed, how much failed, and how much hasn't been processed.  They might not have other functionality than that.

**Comment by damonkelley** [comment]
Cool. So I assume that this will not so much be buttons (since buttons are for clicking), but more badge like? What information will they display? Just the status count?

**Comment by ldko** [comment]
@vphill should they be buttons that filter results by status so, for instance, we can see which items have failed verification?
