### ISSUE TITLE
Allow downloading of zipped bags

### ISSUE THREAD

**Issue by ldko** [unt-libraries/coda#117]
Idea is to allow a user who is viewing a bag to click a button to download a zip file (generated on the fly) of the full bag (not just the bag's data files).

@vphill linked to https://github.com/SpiderOak/ZipStream

**Comment by vphill** [comment]
Here are some different things to read,  different approaches.  

I don't know what will be best.  I do know that we have some big bags in coda, so doing things in memory might not be ideal.  

https://github.com/travcunn/django-zip-stream

https://stackoverflow.com/questions/67454/serving-dynamically-generated-zip-archives-in-django
