### ISSUE TITLE
Add active status for Node

### ISSUE THREAD

**Issue by ldko** [unt-libraries/coda#121]
It would be helpful for storage maintenance/management if we had a `status` field on the `Node` model that would indicate if the node is active/inactive. We could then use it to determine if we want to disable replication to a storage node etc.

**Comment by madhulika95b** [comment]
Do we want to display the `status` field in `node_status.html` page along with rest of the fields?

**Comment by vphill** [comment]
Here is a rough use case that I'm thinking of. 

> In the situation where we need to replace the storage where node-1 is sitting.  We could mark that node as inactive so that we don’t continue adding to it.  We could move it to a new storage location, update the node in the database and then mark it as active again

In this case I think it makes sense to add a column to the node_status.html to show if the node is active/inactive 

For the XML list of active nodes we should not include inactive nodes so that tools that make use of this won't have to change.
