### ISSUE TITLE
Add sorting to storage node stats

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/coda#144]
The storage node status page, controlled by [this view](https://github.com/unt-libraries/coda/blob/master/coda/coda_mdstore/views.py#L730) should allow for sorting on at least the names. This will also require changes to the [template](https://github.com/unt-libraries/coda/blob/master/coda/templates/mdstore/node_status.html).

**Comment by vphill** [comment]
I don't think there is a need to have the user designate the sort in the templates.  We can just define a default sort in the views so that things show up in a logical order.
