### ISSUE TITLE
coda_mdstore ERC support needs refactoring or removal

### ISSUE THREAD

**Issue by ldko** [unt-libraries/coda#20]
In coda_mdstore/views.py, [app_bag] (https://github.com/unt-libraries/coda/blob/master/coda/coda_mdstore/views.py#L849) function has logic for `GET` requests that have an `identifier` to check if the URL has "?" or "??" appended (in support of Electronic Resource Citations (ERC) https://tools.ietf.org/html/draft-kunze-erc-01 spec).

Logic to set value for url_test in the function will exception in mod_wsgi deployments with: `AttributeError: 'WSGIRequest' object has no attribute '_req'`. Our code should not be accessing `_` prefixed attributes anyway. 

Mark's proposed solution (specifically in regard to aubrey not coda) after [this discussion] (https://groups.google.com/forum/#!topic/arks-forum/LIMI699DrdY) was:
Have a rewrite rule that would match a trailing single and double question and have it append something to the URL to let it know on the backend what to do. We would just add a erc_ark/ and erc_commitment/ view to each object--all just on the backend.

But first, do we want to maintain support for ERC in Coda?

**Comment by damonkelley** [comment]
If we keep it, it might be good to put the ERC stuff in it's own app, which we can also use in Aubrey in the future.

**Comment by ldko** [comment]
From Mark:
"We don't need to keep the erc code in coda."

So, we can remove ERC stuff from presentation and views.
