### ISSUE TITLE
Status Code For Invalid Node Path in updateNode

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/coda#23]
In the function `coda_mdstore.presentation.updateNode`, if the request path does not include the node name, an HttpResponse is returned without updating the node. The problem is that the status code returned with the response is 200. Since the request was not `OK` we should set a more correct status code. 

[Snippet](https://github.com/unt-libraries/coda/blob/af9e8ce800cc94aef91bc3c30844bfd1b8d7d786/coda/coda_mdstore/presentation.py#L464-L466)

**Comment by damonkelley** [comment]
Furthermore, we should look at removing the coupling with the request path in the [here](https://github.com/unt-libraries/coda/blob/af9e8ce800cc94aef91bc3c30844bfd1b8d7d786/coda/coda_mdstore/presentation.py#L463)

**Comment by ldko** [comment]
Perhaps a similar status code issue in [updateBag](https://github.com/unt-libraries/coda/blob/af9e8ce800cc94aef91bc3c30844bfd1b8d7d786/coda/coda_mdstore/presentation.py#L128).
