### ISSUE TITLE
XML Model Functions

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/coda#24]
This is a general issue regarding the XML functions for the coda app models. App/Model specific issues may be created at a later date.

The XML functions that take in XML and create or update a model, or functions that take in a model and convert it to XML, should be attached to the models as class methods or static methods. 

Something to keep in mind is that it is possible that these functions will be required outside of the coda project so it might be beneficial to create a base model that extends the `object`, and use multiple inheritance to turn it into a Django model.

``` python
class NodeBase(object):
     # common methods and class variables here

   @classmethod
   def create_from_xml(cls, xml):
        # ...

   @classmethod
   def update_from_xml(cls, xml):
        # ...

class Node(NodeBase, models.Model):
    # django specific stuff here
```

Of course, this would need to be planned out properly so that we don't unintentionally override the inherited methods or variables from `models.Model`.

**Comment by runderwood** [comment]
@ldko I feel like this should be implemented in `codalib`, so the same approach may be used in `coda` and `django_premis_event_service`.

**Comment by ldko** [comment]
Let's try implementing it via codalib then.

**Comment by runderwood** [comment]
OK. Moving this to [codalib #24](https://github.com/unt-libraries/codalib/issues/24).
