### ISSUE TITLE
Clean up md_storeOAIInterface

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/coda#27]
There is a lot we can do to clean up `code_mdstore.mdstore_oai.mdstore_OAIInterface`. The docstring states that it implements the `ResumptionOAIPHM` interface, but it more accurately implements the `IOAI` interface [here](https://github.com/infrae/pyoai/blob/master/src/oaipmh/interfaces.py)

For starters
- Remove `_get_old_solr_getRecord`
- Remove `setAssociations`
- At the very least, rename `listStuff` to something more descriptive. It is more likely that we can remove `listStuff` and just implement the functionality into the two methods that call it.

**Comment by ldko** [comment]
Also, modify listMetadataFormats to include schema and metadataNamespace [here] (https://github.com/unt-libraries/coda/blob/master/coda/coda_mdstore/mdstore_oai.py#L113).

**Comment by runderwood** [comment]
There could be a lot more done here in the way of cleanup and refactoring, but the stuff is functional and the above items have been done as of b2a02976.
