### ISSUE TITLE
Upgrade ResourceSync Implementation to the 1.0 Version of the Spec

### ISSUE THREAD

**Issue by vphill** [unt-libraries/coda#29]
The current Coda ResourceSync implementation used a working draft of the specification. 

Time has passed and there is a 1.0 stable release of the specification which changes a few things here are and there - http://www.openarchives.org/rs/1.0/resourcesync

This ticket will need to be expanded on to identify the areas that specifically need changing.

**Comment by runderwood** [comment]
The examples in the (draft) standard all use content-based hashing. Is there any reason we wouldn't want to take the same approach?

**Comment by runderwood** [comment]
Along w/ this work, per @vphill's request, look into advertising `resourcesync` capabilities/urls.

**Comment by runderwood** [comment]
...and include sort-by-name option.

**Comment by runderwood** [comment]
@vphill The ResourceSync spec, as I read it, says Resource Lists *must* be in chronological order. But I assume it's okay if we break the rules to make a Resource List ordered by **name** to suit our `codatar` needs. Is that alright?

**Comment by vphill** [comment]
If we can have things sort by `bagging_date` then a secondary sort by `name` I think we should be good.

**Comment by runderwood** [comment]
@vphill Not sure if it matters in practice, but our `resourcesync` documents don't validate against the v1.1 XSD. There may be other problems, but the main one right now is the use of `dates` rather than `datetimes` (the spec expects `xsDate`).

**Comment by runderwood** [comment]
I think this is done, at least in the sense that our resource lists validate against the schema (#104). The ordering changes were done in #105.
