### ISSUE TITLE
PUT requests for /APP/queue 500 errors should be handled differently

### ISSUE THREAD

**Issue by ldko** [unt-libraries/coda#33]
In coda_replication at APP/queue (and possibly other coda apps and models--need to check) PUT requests 500 error on a queue entry that doesn't exist. ~~Looking at http://tools.ietf.org/html/rfc2616#section-9.6, we should probably create the object if it doesn't exist and return a 201~~.

**Comment by ldko** [comment]
I had said we should create a resource that doesn't exist if being sent with a PUT because of the [AtomPub spec] (http://bitworking.org/projects/atom/rfc5023.html#edit-via-PUT) saying:
```
 "To edit a Member Resource, a client sends a PUT request to its Member URI,
 as specified in [RFC2616]."
```
which talks about creating a resource that is being PUT if it doesn't exist.

But [later in the AtomPub spec] (http://bitworking.org/projects/atom/rfc5023.html#codeisdata) it says:
```
 "PUT is used to edit a known Resource. It is not used for Resource creation."
```
So perhaps we should 404.

**Comment by vphill** [comment]
I read it as we should 404,  I had the line 

   "PUT is used to edit a known Resource. It is not used for Resource creation."

In my head as well,  POST for create,  PUT for edit and keep to that. If you try and edit something that doesn't exist the user should figure out what they want to do and either ignore or create the resource with POST.

**Comment by ldko** [comment]
Error stems from `HttpResponseNotFound` being referenced in presentation.py where it is not imported.

**Comment by runderwood** [comment]
I've switched the logic in a working branch to return a `409` (conflict) when duplicates are `POST`ed.

`PUT`s for non-existent resources to the queue collection return `404`.

I've switched these error messages to `text/plain`. Does that seem agreeable?

**Comment by ldko** [comment]
That makes sense to me.
