### ISSUE TITLE
Add functionality to filter coda_validate entries based on status

### ISSUE THREAD

**Issue by ldko** [unt-libraries/coda#70]
Rather than add validate `status` filtering functionality with #10 changes, we will wait to add the filtering functionality and are thus making this separate issue.

Being able to filter on `status` will, for example, allow for easily seeing which bags have failed validation.

**Comment by damonkelley** [comment]
Should this filter the _Prioritized Items_, the _Recent Activity_, both?

**Comment by ldko** [comment]
I was thinking this would filter all validate entries just by `last_verified_status` and give a paginated view if necessary. Not sure if @vphill had something else in mind.

**Comment by ldko** [comment]
This is fixed.
