### ISSUE TITLE
Pass `site` to templates via context processor

### ISSUE THREAD

**Issue by ldko** [unt-libraries/coda#86]
Currently using the coda_mdstore base template, the templates for the premis app in this project aren't  getting a `site_title` so the site name is missing in the brand/logo at the top left corner of the premis pages. We could write a context processor that we add to `TEMPLATE_CONTEXT_PROCESSORS` to make the site name available in all the templates (and remove the many places where we are passing `site_title` via views).

This issue came up in discussion about PR #85.

**Comment by damonkelley** [comment]
Currently, we are getting the `site_title` by querying the database for this value. We should consider moving this to the settings file instead.

**Comment by runderwood** [comment]
Closed via #101
