### ISSUE TITLE
Cleanup coda_validate statistics

### ISSUE THREAD

**Issue by ldko** [unt-libraries/coda#9]
On large scale data (we are at just under 1.3 million validate entries), the statistics run very slowly. We should reduce the number of queries used to generate the stats, perhaps by adding a model manager similar to what Damon did in the [name app](https://github.com/unt-libraries/django-name). Also, the stats numbers shown in the two visualizations do not seem to match the text statistics where they should. The "Unverified" in the pie chart doesn't match "Unverified in Queue." The "Passed" in the pie chart doesn't match "Past 365 days" though all validations have been run this year and all passed. The number in the calendar visualization for July 1 do not match the number in "This month."

![coda_validate_unverified_2015-07-01](https://cloud.githubusercontent.com/assets/6740390/8462104/05c5c3d2-1ff7-11e5-9d91-a96a2098d268.jpg)

![coda_validate_passed_2015-07-01](https://cloud.githubusercontent.com/assets/6740390/8462174/86ead29a-1ff7-11e5-9908-ef22bf813117.jpg)

![coda_validate_month_2015-07-01](https://cloud.githubusercontent.com/assets/6740390/8462182/8d7939a8-1ff7-11e5-9fde-1219474c62c8.jpg)

**Comment by ldko** [comment]
Also, when there are validates with status of "Failed" they show up on the pie chart as "Other" in the key. It should probably show up as "Failed".

**Comment by runderwood** [comment]
Also, at the moment, the view attempts to display two years' worth of activity, but the second year is cut in half (see below).

![stats](https://cloud.githubusercontent.com/assets/8513/24048502/1ea4d46e-0af7-11e7-8b20-4be02a79b92e.png)

**Comment by runderwood** [comment]
Stats in production take over four minutes to load. That's just going to get worse, so I'm trying to make it faster (see 6078742).
